project:
  type: website
  output-dir: docs

website:
  title: "Jordan Laura Dewar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: aboutme.qmd
        text: About Me
      - href: research.qmd
        text: Research
      -href: methodology.qmd
        text: Methods
      - href: https://jkbirnir.github.io/GVPT729B/
        text: "GVPT 729B"

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

